name: Spells
main: aor.Spells.Spells
version: 1.0
commands:
   spellinfo:
      description: Gets the description of the current spell, or of the chosen spell.
      usage: |
           /spellinfo [spell]
   listspells:
      description: Lists all of the currently available spells.
      usage: |
           /listspells
   setspell:
      description: Sets your current spell.
      usage: |
           /setspell [spell]