name: SimplePlugin
main: aor.SimplePlugin.SimplePlugin
version: 1.0
commands:
   spellinfo:
      description: Gets the description of the current spell, or of the chosen spell.
      usage: |
           /spellinfo [spell]